### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by robertocommit** [jordipainan/ecardmanjaro#1]
Hi,

many thanks for this, it is crazy there is no official arch support.

I've tried to follow your steps but I lost my self in the section "run this file".

Is it too much right asking you...to make a video tutorial?

Many thanks.

**Comment by jordipainan** [comment]
Hey! This info is outdated. I installed recently the latest eesti card sw using: https://wiki.archlinux.org/index.php/Electronic_identification#Estonia

Hope it helps :)
